# Generated by Django 5.2.1 on 2025-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalexam_lab_test_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexam',
            name='oxygen_saturation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Oxygen saturation in % (e.g., 98)', null=True),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Breaths per minute', null=True),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C (e.g., 36.5)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80 mmHg', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute', null=True),
        ),
    ]
