# Generated by Django 5.2.1 on 2025-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalexam_oxygen_saturation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexam',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute (e.g, 72)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Breaths per minute (e.g, 16)', null=True),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in °C', max_digits=4, null=True),
        ),
    ]
